#!/usr/bin/env bash
#
# Apply the harness schema to a Supabase project.
#
# Deliberately psql and plain .sql files rather than `supabase db push` and a
# migration history: every file in supabase/migrations is safe to re-run, and
# they are applied in order, all of them, every time.
set -euo pipefail

here="$(cd "$(dirname "$0")/.." && pwd)"
migrations=("$here"/supabase/migrations/*.sql)

local_db=0
dry_run=0
bundle=0
for arg in "$@"; do
  case "$arg" in
    --local)   local_db=1 ;;
    --dry-run) dry_run=1 ;;
    --bundle)  bundle=1 ;;
    -h|--help)
      sed -n '3,10p' "$0" | sed 's/^# \{0,1\}//'
      echo
      echo "usage: $0 [--local] [--dry-run] [--bundle]"
      echo "  --bundle writes supabase/setup.sql: every migration in one file, for the dashboard's SQL editor."
      echo "  DATABASE_URL must be set unless --local is given."
      exit 0 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

if [ ! -f "${migrations[0]}" ]; then
  echo "no migrations in $here/supabase/migrations" >&2
  exit 1
fi

if [ "$bundle" -eq 1 ]; then
  {
    echo "-- The whole harness schema in one file, for the Supabase dashboard: SQL Editor -> New query -> paste -> Run."
    echo "-- It is supabase/migrations/*.sql in order (generated by scripts/apply-schema.sh --bundle); safe to run"
    echo "-- again. The last line tells the API to reload, so the phone's Saved list (the phone_lectures view) is"
    echo "-- found at once instead of \"Could not find the table ... in the schema cache\"."
    echo
    for migration in "${migrations[@]}"; do
      echo "-- ===== $(basename "$migration") ====="
      cat "$migration"
      echo
    done
    echo "-- Reload the API's schema cache: new tables and views are served at once."
    echo "notify pgrst, 'reload schema';"
  } > "$here/supabase/setup.sql"
  echo "wrote $here/supabase/setup.sql"
  exit 0
fi

if [ "$local_db" -eq 1 ]; then
  # What `supabase start` serves by default.
  url="${DATABASE_URL:-postgresql://postgres:postgres@127.0.0.1:54322/postgres}"
else
  url="${DATABASE_URL:-}"
fi

if [ "$dry_run" -eq 1 ]; then
  # A dry run reports, it does not require: someone checking what this would do
  # should not have to produce a database URL first.
  for migration in "${migrations[@]}"; do
    echo "would apply $(basename "$migration") ($(wc -l < "$migration") lines)"
  done
  if [ -n "$url" ]; then
    echo "to ${url##*@}"          # host and database, never the password
  else
    echo "to: nowhere -- DATABASE_URL is unset and --local was not given"
  fi
  exit 0
fi

if [ -z "$url" ]; then
  echo "DATABASE_URL is not set, and --local was not given." >&2
  echo "Find it under Project Settings -> Database -> Connection string." >&2
  exit 1
fi

if ! command -v psql > /dev/null; then
  echo "psql not found. Install the postgresql client, or run the SQL in" >&2
  echo "supabase/migrations, in order, through the Supabase dashboard's SQL editor." >&2
  exit 1
fi

# ON_ERROR_STOP because a half-applied schema is worse than none: without it
# psql reports success after skipping every statement that failed.
for migration in "${migrations[@]}"; do
  echo "applying $(basename "$migration")"
  psql "$url" --single-transaction -v ON_ERROR_STOP=1 -f "$migration"
done
# The API caches the schema: without this, a new view answered "not in the schema cache" for a while.
psql "$url" -v ON_ERROR_STOP=1 -c "notify pgrst, 'reload schema';" > /dev/null
echo "done"
