-- The whole harness schema in one file, for the Supabase dashboard: SQL Editor -> New query -> paste -> Run.
-- It is supabase/migrations/*.sql in order (generated by scripts/apply-schema.sh --bundle); safe to run
-- again. The last line tells the API to reload, so the phone's Saved list (the phone_lectures view) is
-- found at once instead of "Could not find the table ... in the schema cache".

-- ===== 0001_init.sql =====
-- Harness schema.
--
-- Shape of the thing: a user brings CONTENT and picks a TEMPLATE. That
-- produces SCENES, each of which has a transcript and a chain of SCENE
-- VERSIONS -- Manim source, one version per instruction the user gives.
-- Exporting a version produces a BUILD: a .panim program, its ASSETS, and a
-- tier verdict. Source and program are separate on purpose; one is what a
-- human edits and the other is what a phone plays.
--
-- Safe to re-run. Every statement is guarded, because this is applied by hand
-- against projects someone has already touched.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

do $$ begin
  create type build_state as enum ('pending', 'running', 'succeeded', 'failed');
exception when duplicate_object then null; end $$;

-- Which tier the exporter reached. 1 is a program of a few hundred bytes; 3 is
-- sampled frames, which on the corpus measured about a thousand times larger
-- for the same scene. It is a first-class column because a user should be able
-- to see that difference, and because a silent fall to 3 is the main way
-- generation goes wrong without anything appearing to break.
do $$ begin
  create type scene_tier as enum ('tier1', 'tier3');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- Templates: the kinds of video that can be made
-- ---------------------------------------------------------------------------

create table if not exists templates (
  id           uuid primary key default gen_random_uuid(),
  slug         text not null unique,
  name         text not null,
  description  text,

  -- Look. Separated from the prompt so a palette can be swapped without
  -- rewriting the instructions that shape the animation.
  palette      jsonb not null default '{}'::jsonb,
  typography   jsonb not null default '{}'::jsonb,
  pacing       jsonb not null default '{}'::jsonb,

  -- What the model is told, and what it is given to start from. The preamble
  -- is real Python prepended to generated source -- imports and helpers a
  -- template guarantees are present, so the model never has to guess whether
  -- cartopy is available.
  prompt       text not null default '',
  preamble     text not null default '',

  -- Python the worker must have installed for this template to export at all.
  -- A map template needs cartopy; a molecule template does not.
  requires     text[] not null default '{}',

  is_builtin   boolean not null default false,
  owner_id     uuid references auth.users (id) on delete cascade,
  created_at   timestamptz not null default now(),

  -- A built-in belongs to everyone, so it has no owner. Anything else must.
  constraint templates_ownership check (is_builtin = (owner_id is null))
);

-- ---------------------------------------------------------------------------
-- Projects: the content a user brought, and what to make of it
-- ---------------------------------------------------------------------------

create table if not exists projects (
  id           uuid primary key default gen_random_uuid(),
  owner_id     uuid not null references auth.users (id) on delete cascade,
  title        text not null default 'Untitled',
  content      text not null default '',
  template_id  uuid references templates (id) on delete restrict,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists projects_owner_idx on projects (owner_id, updated_at desc);

-- ---------------------------------------------------------------------------
-- Scenes: one Manim Scene each, ordered within a project
-- ---------------------------------------------------------------------------

create table if not exists scenes (
  id            uuid primary key default gen_random_uuid(),
  project_id    uuid not null references projects (id) on delete cascade,
  ordinal       integer not null,

  -- The name the exporter will know it by: a Python class name, so it has to
  -- be one. Checked here rather than discovered when export fails.
  class_name    text not null check (class_name ~ '^[A-Z][A-Za-z0-9_]*$'),
  title         text not null default '',

  -- What the scene says, as opposed to what it draws. The natural place for a
  -- human to steer meaning rather than visuals.
  transcript    text not null default '',

  created_at    timestamptz not null default now(),
  unique (project_id, ordinal),
  unique (project_id, class_name)
);

-- ---------------------------------------------------------------------------
-- Scene versions: the edit history, one version per instruction
-- ---------------------------------------------------------------------------

create table if not exists scene_versions (
  id           uuid primary key default gen_random_uuid(),
  scene_id     uuid not null references scenes (id) on delete cascade,
  version      integer not null,

  -- The Manim Python. The artifact of record on the source side.
  source       text not null,

  -- What the user asked for to get here. Null on the first version, which
  -- nothing asked for. This is the edit loop: a human gives an instruction, a
  -- version comes back, and the chain is the history of that conversation.
  instruction  text,
  parent_id    uuid references scene_versions (id) on delete set null,

  -- Provenance. Which model wrote it, and what it cost.
  model        text,
  input_tokens  integer,
  output_tokens integer,

  created_at   timestamptz not null default now(),
  unique (scene_id, version)
);

create index if not exists scene_versions_scene_idx
  on scene_versions (scene_id, version desc);

-- ---------------------------------------------------------------------------
-- Assets: content-addressed, shared across everything
-- ---------------------------------------------------------------------------

-- The glyph atlas is one file every text scene points at, so assets are keyed
-- by digest and shared rather than copied per build. Bytes live in Supabase
-- Storage under the digest; this table is the index.
create table if not exists assets (
  digest       text primary key check (digest ~ '^[0-9a-f]{10,64}$'),
  byte_size    bigint not null check (byte_size >= 0),
  content_type text not null default 'application/octet-stream',
  created_at   timestamptz not null default now(),

  -- The brief's one hard prohibition, made an invariant rather than a
  -- convention: no rendered video is ever stored. A schema that cannot hold it
  -- is a stronger guarantee than a rule someone has to remember.
  constraint assets_no_video check (content_type not like 'video/%')
);

-- ---------------------------------------------------------------------------
-- Builds: exporting a version, and what came back
-- ---------------------------------------------------------------------------

create table if not exists builds (
  id                uuid primary key default gen_random_uuid(),
  scene_version_id  uuid not null references scene_versions (id) on delete cascade,
  state             build_state not null default 'pending',

  tier              scene_tier,

  -- The exporter's own verdict, carried through rather than re-derived: it
  -- writes a blockers array naming each thing it could not express. That list
  -- is what tells a user why their scene is large, and it is the only honest
  -- source for it.
  blockers          jsonb not null default '[]'::jsonb,

  -- The .panim program, in Storage under this key. Small enough to inline,
  -- but kept beside the assets so one mechanism serves both.
  program_path      text,
  program_bytes     integer,
  frame_count       integer,
  fps               integer,

  started_at        timestamptz,
  finished_at       timestamptz,
  duration_ms       integer,
  error             text,
  created_at        timestamptz not null default now(),

  -- A build that succeeded has a tier and a program; one that failed has
  -- neither and should say why. Enforced because "succeeded with no output" is
  -- the state that wastes the most time to debug.
  constraint builds_succeeded_is_complete check (
    state <> 'succeeded' or (tier is not null and program_path is not null)
  ),
  constraint builds_failed_explains_itself check (
    state <> 'failed' or error is not null
  )
);

create index if not exists builds_version_idx
  on builds (scene_version_id, created_at desc);

-- Which assets a build needs. Many-to-many because assets are shared: two
-- scenes with text point at the same atlas.
create table if not exists build_assets (
  build_id  uuid not null references builds (id) on delete cascade,
  digest    text not null references assets (digest) on delete restrict,
  primary key (build_id, digest)
);

-- ---------------------------------------------------------------------------
-- Row-level security: everything is owned, nothing is shared by default
-- ---------------------------------------------------------------------------

alter table templates      enable row level security;
alter table projects       enable row level security;
alter table scenes         enable row level security;
alter table scene_versions enable row level security;
alter table builds         enable row level security;
alter table assets         enable row level security;
alter table build_assets   enable row level security;

-- Built-in templates are readable by anyone signed in; a user's own are theirs.
drop policy if exists templates_read on templates;
create policy templates_read on templates for select
  to authenticated using (is_builtin or owner_id = auth.uid());

drop policy if exists templates_write on templates;
create policy templates_write on templates for all
  to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());

drop policy if exists projects_own on projects;
create policy projects_own on projects for all
  to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());

-- Everything below a project inherits its ownership. Written as an exists
-- against the chain rather than a denormalised owner column, so there is one
-- place ownership is defined and no way for the copies to disagree.
drop policy if exists scenes_own on scenes;
create policy scenes_own on scenes for all to authenticated
  using (exists (select 1 from projects p
                 where p.id = scenes.project_id and p.owner_id = auth.uid()))
  with check (exists (select 1 from projects p
                      where p.id = scenes.project_id and p.owner_id = auth.uid()));

drop policy if exists scene_versions_own on scene_versions;
create policy scene_versions_own on scene_versions for all to authenticated
  using (exists (select 1 from scenes s join projects p on p.id = s.project_id
                 where s.id = scene_versions.scene_id and p.owner_id = auth.uid()))
  with check (exists (select 1 from scenes s join projects p on p.id = s.project_id
                      where s.id = scene_versions.scene_id and p.owner_id = auth.uid()));

drop policy if exists builds_own on builds;
create policy builds_own on builds for all to authenticated
  using (exists (select 1 from scene_versions v
                 join scenes s on s.id = v.scene_id
                 join projects p on p.id = s.project_id
                 where v.id = builds.scene_version_id and p.owner_id = auth.uid()))
  with check (exists (select 1 from scene_versions v
                      join scenes s on s.id = v.scene_id
                      join projects p on p.id = s.project_id
                      where v.id = builds.scene_version_id and p.owner_id = auth.uid()));

-- Assets are content-addressed and therefore not secret: the digest is the
-- capability. Readable by anyone signed in, writable only by the service role,
-- which is the worker. A client that could insert asset rows could lie about
-- what a build contains.
drop policy if exists assets_read on assets;
create policy assets_read on assets for select to authenticated using (true);

drop policy if exists build_assets_read on build_assets;
create policy build_assets_read on build_assets for select to authenticated
  using (exists (select 1 from builds b
                 join scene_versions v on v.id = b.scene_version_id
                 join scenes s on s.id = v.scene_id
                 join projects p on p.id = s.project_id
                 where b.id = build_assets.build_id and p.owner_id = auth.uid()));

-- ---------------------------------------------------------------------------
-- Housekeeping
-- ---------------------------------------------------------------------------

create or replace function touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists projects_touch on projects;
create trigger projects_touch before update on projects
  for each row execute function touch_updated_at();

-- ===== 0002_saved_lectures.sql =====
-- Saved lectures, and the phone's catalog of them.
--
-- What changed since 0001: a lecture is now made as a series of micro-lectures (app/lib/topics.ts), one video
-- per topic, and a user saves it with Save. A saved lecture is a PROJECT (the series); each of its videos is a
-- SCENE (ordinal = its place in the series), with the version that was saved and the BUILD exported from it.
-- The build's phone library -- the .panim program, its assets, the glyph atlas and the narration, the same
-- folder the player opens (tools/build_library.py) -- is in Supabase Storage, in the bucket `lectures`:
--
--   builds/<build id>/library.json, scenes/<Scene>.panim, scenes/<Scene>.json, library.atlas, audio/<Scene>.wav
--   assets/<digest>.panm              content-addressed, shared by every build that uses it (the assets table)
--
-- The library's own "assets/<digest>.panm" paths are read from the shared folder at the bucket's root.
--
-- The phone lists what has been saved from the view `phone_lectures` and downloads a lecture's folder. Safe to
-- re-run, like 0001.

-- ---------------------------------------------------------------------------
-- Projects: what a saved lecture is about
-- ---------------------------------------------------------------------------

alter table projects add column if not exists subject  text;
alter table projects add column if not exists language text;
alter table projects add column if not exists minutes  numeric;

-- ---------------------------------------------------------------------------
-- Scenes: one per video of a series
-- ---------------------------------------------------------------------------

-- Every lecture video's Python class is GeneratedScene: the parts of a series share it, and the ordinal is what
-- tells them apart (unique (project_id, ordinal) stays).
alter table scenes drop constraint if exists scenes_project_id_class_name_key;

alter table scenes add column if not exists minutes numeric;
-- The series it belongs to: "Lecture 2 of 3".
alter table scenes add column if not exists part_of integer check (part_of is null or part_of >= 1);

-- ---------------------------------------------------------------------------
-- Builds: where the phone library is, and whether the phone may list it
-- ---------------------------------------------------------------------------

-- The library folder in the `lectures` bucket (builds/<build id>), its size, and the narration in it.
alter table builds add column if not exists library_path  text;
alter table builds add column if not exists library_bytes bigint check (library_bytes is null or library_bytes >= 0);
alter table builds add column if not exists audio_path    text;
-- Saved for the phone. Only a succeeded tier-1 build with its library uploaded may be: the phone plays programs,
-- and a row it cannot download is a dead entry in its list.
alter table builds add column if not exists published     boolean not null default false;

do $$ begin
  alter table builds add constraint builds_published_is_playable check (
    not published or (state = 'succeeded' and tier = 'tier1' and library_path is not null)
  );
exception when duplicate_object then null; end $$;

create index if not exists builds_published_idx on builds (finished_at desc) where published;

-- ---------------------------------------------------------------------------
-- The phone's catalog
-- ---------------------------------------------------------------------------

-- What the player app lists: every published lecture video, newest series first, its videos in order. A view so
-- the phone (signed in or not, with the project's anon key) reads exactly these columns of exactly these rows;
-- the tables' own policies still keep everything else to its owner. It runs with its owner's rights, which is
-- what lets the anon role read the published rows and nothing more.
create or replace view phone_lectures as
select
  b.id               as build_id,
  p.id               as project_id,
  p.title            as series,
  p.subject          as subject,
  p.language         as language,
  s.ordinal          as lecture,
  coalesce(s.part_of, 1) as lectures,
  coalesce(nullif(s.title, ''), p.title) as title,
  s.minutes          as minutes,
  b.library_path     as library_path,
  b.library_bytes    as library_bytes,
  b.program_bytes    as program_bytes,
  b.frame_count      as frame_count,
  b.fps              as fps,
  (b.audio_path is not null) as narrated,
  b.finished_at      as saved_at
from builds b
join scene_versions v on v.id = b.scene_version_id
join scenes s on s.id = v.scene_id
join projects p on p.id = s.project_id
where b.published;

do $$ begin
  grant select on phone_lectures to anon;
exception when undefined_object then null; end $$;
do $$ begin
  grant select on phone_lectures to authenticated;
exception when undefined_object then null; end $$;

-- ---------------------------------------------------------------------------
-- Storage: the bucket the libraries are in
-- ---------------------------------------------------------------------------

-- Public for reading: a library's path holds its build's random id, and the phone downloads it without signing
-- in. Writing is the service role's alone (the web app's Save), as for the assets table. Skipped where there is
-- no Supabase Storage (a bare Postgres in harness/scripts/test-schema.sh).
do $$ begin
  if to_regclass('storage.buckets') is not null then
    insert into storage.buckets (id, name, public)
    values ('lectures', 'lectures', true)
    on conflict (id) do update set public = true;
  end if;
end $$;

-- ===== 0003_generated_media.sql =====
-- Everything a lecture generation makes, kept by default (app/lib/media.ts), so runs can be saved and compared.
--
-- What changed since 0002: until now nothing was stored until the user pressed Save, and then only the phone
-- library. Now, as a lecture is made, the server keeps (PANIM_STORE_MEDIA=0 turns it off):
--
--   GENERATIONS        one row per lecture made: what it was asked, the models, its length and cost.
--   MEDIA              every picture it made or used, once per distinct file (content-addressed by its SHA-256):
--                      SVG drawings, book figures redrawn as SVG, AI illustrations, book photos and the web
--                      photos found like them, and the web and library pictures the compiler fetched. Each with
--                      what it shows (description) and where it came from (source, credit, licence, model).
--   GENERATION_MEDIA   where each picture was used in a generation: the chapter, the line said over it, the
--                      section, the diagram node or map label it sits beside, what it cost. A file used twice is
--                      two rows here and one in MEDIA.
--   GENERATION_SCENES  each video's Manim source, as the generation wrote it.
--   PROGRAMS           each .panim program built from a scene (every build, not only saved ones), with its frames
--                      and size, linked to its generation through the scene source's digest.
--
-- The files are in the private Storage bucket `media`:
--
--   media/<sha256>.<ext>              a picture (svg, png, jpg, webp); its kind and description are in MEDIA
--   programs/<sha256>.panim           a program
--
-- Written by the server's service role alone; nothing here is for the phone. Safe to re-run, like 0001 and 0002.

-- ---------------------------------------------------------------------------
-- Generations
-- ---------------------------------------------------------------------------

create table if not exists generations (
  id                text primary key,                    -- the generate job's id (lib/jobs.ts)
  created_at        timestamptz not null default now(),
  finished_at       timestamptz,
  title             text,
  template          text,
  model             text,
  transcript_model  text,
  svg_model         text,
  subject           text,
  language          text,
  art               text,
  minutes           numeric,                             -- asked for, or estimated from the source
  videos            integer check (videos is null or videos >= 1),
  cost_usd          numeric check (cost_usd is null or cost_usd >= 0),
  request           jsonb not null default '{}'::jsonb,  -- the content (shortened), the document, the options
  state             text not null default 'running' check (state in ('running', 'finished', 'failed', 'stopped')),
  error             text
);

create index if not exists generations_created_idx on generations (created_at desc);

-- ---------------------------------------------------------------------------
-- Media: each distinct picture once
-- ---------------------------------------------------------------------------

create table if not exists media (
  digest        text primary key check (digest ~ '^[0-9a-f]{64}$'),   -- SHA-256 of the file
  kind          text not null check (kind in (
                  'drawing',        -- a picture the lecture asked for, drawn as SVG (lib/drawings.ts)
                  'figure',         -- a book figure redrawn as SVG (lib/figures.ts)
                  'book-figure',    -- a book figure as the document has it (built in Manim instead)
                  'book-photo',     -- a book photograph, shown as it is
                  'photo',          -- a real photo: the web's like a book photo, or one the lecture asked for
                  'illustration'    -- an illustration: a library's, or one an image model drew
                )),
  content_type  text not null,
  byte_size     bigint not null check (byte_size >= 0),
  storage_path  text not null unique,                   -- in the `media` bucket
  description   text not null,                          -- what it shows
  metadata      jsonb not null default '{}'::jsonb,     -- parts, source, credit, licence, url, model
  created_at    timestamptz not null default now()
);

create index if not exists media_kind_idx on media (kind, created_at desc);

-- ---------------------------------------------------------------------------
-- Where each picture was used
-- ---------------------------------------------------------------------------

create table if not exists generation_media (
  id             bigint generated always as identity primary key,
  generation_id  text not null references generations (id) on delete cascade,
  digest         text not null references media (digest) on delete cascade,
  role           text not null,                         -- drawn, book figure, beside a label, a beat's photo...
  context        jsonb not null default '{}'::jsonb,    -- chapter, section, line said, diagram node, query
  usd            numeric check (usd is null or usd >= 0),
  reused         boolean not null default false,        -- found already made (a cache): nothing paid this run
  created_at     timestamptz not null default now()
);

create index if not exists generation_media_generation_idx on generation_media (generation_id);
create index if not exists generation_media_digest_idx on generation_media (digest);

-- ---------------------------------------------------------------------------
-- Scenes and programs
-- ---------------------------------------------------------------------------

create table if not exists generation_scenes (
  generation_id  text not null references generations (id) on delete cascade,
  part           integer not null check (part >= 1),    -- its place in the series (1 for a single video)
  title          text,
  minutes        numeric,
  source_digest  text not null check (source_digest ~ '^[0-9a-f]{64}$'),  -- SHA-256 of the Manim source
  source         text not null,
  created_at     timestamptz not null default now(),
  primary key (generation_id, source_digest)            -- a renumbered video is a source of its own
);

create index if not exists generation_scenes_source_idx on generation_scenes (source_digest);

create table if not exists programs (
  id             bigint generated always as identity primary key,
  digest         text not null check (digest ~ '^[0-9a-f]{64}$'),         -- SHA-256 of the .panim
  storage_path   text not null,                         -- in the `media` bucket
  byte_size      bigint not null check (byte_size >= 0),
  scene_class    text not null,
  source_digest  text not null check (source_digest ~ '^[0-9a-f]{64}$'),  -- the scene it was built from
  generation_id  text references generations (id) on delete set null,     -- when that scene came from one
  title          text,
  tier           integer,
  frames         integer check (frames is null or frames >= 0),
  narrated       boolean not null default false,
  build_seconds  integer,
  created_at     timestamptz not null default now()
);

create index if not exists programs_generation_idx on programs (generation_id, created_at desc);
create index if not exists programs_source_idx on programs (source_digest);

-- ---------------------------------------------------------------------------
-- Access: the server alone (its service role passes row-level security); no policy lets anyone else in.
-- ---------------------------------------------------------------------------

alter table generations       enable row level security;
alter table media             enable row level security;
alter table generation_media  enable row level security;
alter table generation_scenes enable row level security;
alter table programs          enable row level security;

-- The bucket: private (book figures and web photos keep their own licences; nothing here is published).
do $$ begin
  if to_regclass('storage.buckets') is not null then
    insert into storage.buckets (id, name, public)
    values ('media', 'media', false)
    on conflict (id) do nothing;
  end if;
end $$;

-- Reload the API's schema cache: new tables and views are served at once.
notify pgrst, 'reload schema';
